version: '3.8'
services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'

  app:
    build: .
    depends_on:
      - redis
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
